version: '3.9'
services:
  mysql:
    image: mysql:9.0
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-volume:
  redis-data:
    driver: local