version: '3.9'
services:
  mysql-kc:
    image: mysql:9.0
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - keycloak-and-mysql-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:

  redis-data:
    driver: local
