
export enum UnoGatewayEventEmit {

  UNO_DECLARED = 'UNO_DECLARED',
  UNO_COUNTERED = 'UNO_COUNTERED',
  GAME_STATE = 'GAME_STATE',
  CARD_PLAYED = 'CARD_PLAYED',
  CARD_DRAWN = 'CARD_DRAWN',
  GAME_STARTED = 'GAME_STARTED',
  GAME_CREATED = 'GAME_CREATED',
  GAME_ENDED = 'GAME_ENDED',
  PRIVATE_STATE= "PRIVATE_STATE",
}